<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/5.0.1/Rx.js"></script>
  </head>
  <body>
    <script>
      var source = Rx.Observable.from(['a', 'b', 'c', 'd', 2])
        .zip(Rx.Observable.interval(500), (x, y) => x)
        .map((x) => x.toUpperCase())
        // 錯誤處理 : errorObs : 不是原本的 observable source ，而是由例外事件組成的observable
        // 等到處理完成後，延遲1000後會重新訂閱source
        .retryWhen((errorObs) => errorObs.delay(1000));

      // var example = source.map((x) => x.toUpperCase()).catch((error) => Rx.Observable.of('h'));

      source.subscribe(
        (res) => console.log(res),
        (err) => console.log('error : ' + err),
        () => console.log('complete')
      );
    </script>
  </body>
</html>
